/* =============================================================
   SERIALISER — model back to content files.

   The editor's output must be byte-plausible content: the same
   shape a person would hand-write, so the files stay readable and
   diffable and you can always drop back to editing them directly.

   Author comments inside data cannot survive a round trip through
   objects, so each file gets a regenerated header instead.
   ============================================================= */

const Serialise = (function () {
  "use strict";

  const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

  function str(s) {
    if (String(s).includes("\n")) return "`" + String(s).replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
    return '"' + String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
  }

  function val(v, ind, inline) {
    if (v === null) return "null";
    if (typeof v === "number" || typeof v === "boolean") return String(v);
    if (typeof v === "string") return str(v);
    if (Array.isArray(v)) {
      if (!v.length) return "[]";
      const flat = v.every(x => typeof x !== "object" || x === null);
      if (flat || inline) return "[" + v.map(x => val(x, ind, true)).join(",") + "]";
      return "[\n" + v.map(x => ind + "  " + val(x, ind + "  ")).join(",\n") + "\n" + ind + "]";
    }
    const keys = Object.keys(v).filter(k => v[k] !== undefined);
    if (!keys.length) return "{}";
    const short = keys.every(k => typeof v[k] !== "object" || v[k] === null) &&
                  keys.map(k => k + String(v[k])).join("").length < 70;
    const body = keys.map(k => (IDENT.test(k) ? k : str(k)) + ":" + val(v[k], ind + "  ", short || inline));
    if (short || inline) return "{ " + body.join(", ") + " }";
    return "{\n" + body.map(b => ind + "  " + b).join(",\n") + "\n" + ind + "}";
  }

  /* one entry per line-ish, matching the hand-written files */
  function list(name, arr, header) {
    return header + "\nconst " + name + " = [\n\n" +
      arr.map(o => "  " + val(o, "  ")).join(",\n\n") + "\n\n];\n";
  }

  const H = {
    events:
`/* ============================================================
   EVENTS — generated by the editor. Safe to hand-edit.
   Verbs: move law station seats flag bill
          relationship coalition wire queue
   Conditions: minSitting maxSitting flags flagsAbsent scalarAbove
          scalarBelow lawIs lawAbove lawBelow loyaltyAbove
          loyaltyBelow billStage inGovernment
   prologue:N  fires in order at the start, teaching one cluster
   queuedOnly  reachable only from a queue effect
   ============================================================ */`,
    parties:
`/* PARTIES — generated by the editor.
   axes: ownership public|private · personhood expansionist|restrictionist
         sovereignty federal|station · closure closurist|integrationist
   aliases: press nicknames (bible 8.3) */`,
    stations:
`/* STATIONS AND CONSTITUENCIES — generated by the editor.
   Roster is frozen canon. Adding one is a deliberate act. */`,
    characters:
`/* CHARACTERS — generated by the editor. The fixed roster. */`,
    bills:
`/* BILLS — generated by the editor.
   stances: "for" | "against" | "abstain" | {for:n} | {forPct:0..1}
            | {free:true} | {popular:…, functional:…}
   dualMajority:true must carry separately on both benches. */`,
    functional:
`/* FUNCTIONAL CONSTITUENCIES — generated by the editor.
   franchise: licensure | corporate | union_bloc | residual
   held must reconcile with each party's functional seat count. */`,
    constituencies:
`/* CONSTITUENCIES — the district tier. Generated by the editor.
   magnitude sums to the district tier (140) and, per station, to that
   station's seat count. electorate is attested adults, not population.
   apportionment_ratio is NOT stored: Engine.apportionment() derives it. */`,
    glossary:
`/* GLOSSARY — generated by the editor.
   cluster: terms that cannot be taught apart count as ONE unit of
   teaching load. The rule is one cluster per event. */`,
    settlements:
`/* =============================================================
   SETTLEMENTS — the endings. Generated by the editor. Bible §3.5.1.
     1. A settlement is a \`when\` block, read by the same matches()
        every event uses.
     2. THE PLAYER IS NEVER SHOWN THE LIST.
     3. Closure and dissolution are failure modes, not settlements.
     4. The record makes a settlement cheaper or dearer, never impossible.
   rank     decides between two that hold at once: lower is read first
   crisis   true: a campaign's crisis result, kept in resolvedAs once and
            for good; otherwise an answer, kept in settledAs
   closing  the ending itself, written as though it were the only one
   ============================================================= */`,
    initiatives:
`/* =============================================================
   INITIATIVES — what the government puts in motion. Generated by
   the editor.
     cost    order-paper slots, before the tempo's own surcharge
     when    the same condition vocabulary events use
     event   the answer, queued \`after\` sittings by the chosen tempo
     tempo   [{ label, after, cost?, effects?, when? }] -- a tempo's own
             \`when\` closes that way of doing it without closing the others
   TEMPO IS THE DECISION: give tempos different effects, not only speeds.
   ============================================================= */`,
    cabinet:
`/* =============================================================
   THE CABINET — the posts. Generated by the editor.
     name       the ministry; title  the minister's title
     holder     a character id, or null when the post is vacant
     party      the holder's party; senior, apart as the post sits
     brief      the subjects it answers for: meters, price.<k>, laws
     vacatedBy, candidates  who left it, and who may fill it and at what
   Instruments name a post as their \`author\`.
   ============================================================= */`,
    instruments:
`/* =============================================================
   INSTRUMENTS — orders a post makes without a bill. Generated by
   the editor.
     procedure      negative: in force when laid, annulled on a prayer
                    within prayer_window sittings; affirmative: in force
                    when the House approves (approvalFloor: how much of a
                    government bench holds whatever its loyalty)
     effects        what it does; reverse, what revoking undoes;
     political_cost what laying it costs whatever happens after
     prayer_stances each party's vote on the prayer or the approval
     when           the rung below tried, for a ladder
   ============================================================= */`,
    forums: `/* =============================================================
   THE FORUMS (design/43) — chambers the Commonwealth sits in and does
   not command. The engine names no forum; everything it knows about
   one is here.

     members        states and blocs, each with
       votes        how many seats it casts
       axes         its position on the forum's axes, -1 .. +1
       standing     toward the Commonwealth, 0 .. 100, 50 indifferent
       cohesion     for a bloc, the share of its votes that follow its
                    line; the rest abstain. A state is 1.
       actor        an actor whose standing this member reads and moves
       self         the Commonwealth's own seat
     firstAfter     days from the campaign's opening to the first sitting
     every          days between sittings
     majority       of those present and voting; 0.5 is a simple majority
     line           how far a member must lean to vote rather than abstain
     standingWeight how much standing turns a vote toward the Commonwealth's
     climate        [{from, at, weight}]: what every member reads besides
                    its own standing, from a meter

     summary        the Concordance's lede, continuing from the name

   RESOLUTIONS are put to a forum:
     forum, sponsor (a member id), title, summary,
     axes           the resolution's position on the forum's axes
     majority       overrides the forum's (two thirds is 0.6667)
     when           for the Commonwealth's own: when it may be tabled
     whenText       why it cannot be yet, for the Table control
     stances        {member: "for" | "against" | "abstain"}, fixed votes
     vote           the Commonwealth's vote until the government sets one
                    (its own are "for"; anything else "abstain" by default)
     onTable, onPass, onFail   effects
   The world's are here; a campaign's are in its folder.
   Generated by the editor.
   ============================================================= */`,
    achievements:
`/* =============================================================
   ACHIEVEMENTS — awards, judged once on the finished record by
   js/shell.js meets(). Generated by the editor.
     tier   ending | settlement | action | canon
     when   end, reason, seats, settled, resolved, kept, breached,
            flags, flagsAny, log, logAbsent: every key must hold
   ============================================================= */`
  };

  function file(kind, arr) {
    const name = { events:"EVENTS", parties:"PARTIES", stations:"STATIONS",
                   characters:"CHARACTERS", bills:"BILLS", glossary:"GLOSSARY",
                   functional:"FUNCTIONAL", constituencies:"CONSTITUENCIES",
                   settlements:"SETTLEMENTS", initiatives:"INITIATIVES",
                   achievements:"ACHIEVEMENTS", cabinet:"CABINET",
                   instruments:"INSTRUMENTS" }[kind];
    return list(name, arr, H[kind]);
  }

  /* WHICH FILE AN ENTRY IS KEPT IN. A campaign's entries live in its folder,
     content/campaigns/<id>/<kind>.js, each file one `campaign()` call that
     tags what it hands over (content/setup.js). So the editor writes the
     world's entries to the world's file and each campaign's to its own, and
     leaves out of a campaign file the tag its wrapper will put back: the
     entry reloads exactly as it went out, which tools/roundtrip.js asserts.
     An entry naming several campaigns is kept with the first. */
  function home(x) {
    const c = x && x.campaign;
    return typeof c === "string" ? c : Array.isArray(c) && c.length ? c[0] : null;
  }
  function untag(x, id) {
    if (!x || x.campaign !== id) return x;
    const o = {};
    Object.keys(x).forEach(k => { if (k !== "campaign") o[k] = x[k]; });
    return o;
  }
  function campaignFile(id, kind, arr) {
    return `/* ${id.toUpperCase()}: ${kind.toUpperCase()}. Generated by the editor.
   Kept at content/campaigns/${id}/${kind}.js. Every entry here is the
   campaign's: campaign() in content/setup.js tags it and adds it to the
   world's list. */
campaign(${str(id)}, { ${kind}: [

` + arr.map(o => "  " + val(untag(o, id), "  ")).join(",\n\n") + `

] });
`;
  }
  /* One kind as the files it is kept in: [{ path, text }], the world's
     first. `write(worldEntries)` draws the world's file. */
  function split(kind, arr, write) {
    const world = [], camps = {};
    arr.forEach(x => { const c = home(x); if (c) (camps[c] = camps[c] || []).push(x); else world.push(x); });
    return [{ path: "content/" + (kind === "articles" ? "encyclopedia" : kind) + ".js", text: write(world) }]
      .concat(Object.keys(camps).map(c => ({ path: "content/campaigns/" + c + "/" + kind + ".js",
                                            text: campaignFile(c, kind, camps[c]) })));
  }
  function files(kind, arr) { return split(kind, arr, w => file(kind, w)); }
  function encyclopediaFiles(enc) {
    return split("articles", enc.articles,
                 w => encyclopediaFile(Object.assign({}, enc, { articles: w })));
  }

  /* THE CAMPAIGN RECORD: every administration, in the folder of the
     campaign it plays (content/campaigns/<id>/campaign.js). Not `files()`:
     an administration's `campaign` field says which campaign it PLAYS, not
     whose it is (the sandbox plays Flash I and is kept with it), so it is
     never untagged, and one with no `campaign` is kept in a folder of its
     own name. */
  function administrationsFiles(arr) {
    const by = {};
    (arr || []).forEach(a => {
      const c = (typeof a.campaign === "string" && a.campaign) || a.id;
      (by[c] = by[c] || []).push(a);
    });
    return Object.keys(by).map(c => ({ path: "content/campaigns/" + c + "/campaign.js", text:
`/* =============================================================
   ${c.toUpperCase()}: THE CAMPAIGN. Generated by the editor.

   Who opens it, and anything that plays it. Each administration is a
   government the menu offers:
     party, leader      the governing party and the Prime Minister
     ordinal, from, to  which term, and its years, for the label
     session            which session of the term the campaign opens at
     campaign           the campaign it plays, when not its own (a sandbox)
     setup              merged ONE LEVEL deep over the world's setup
     opening            effects applied at the first sitting
     intro              the introduction, drawn by js/setpiece.js

   Add every file in this folder to index.html AND editor.html, after the
   world's content and before content/index.js (CONTENT_GUIDE.md).
   ============================================================= */
campaign(${str(c)}, { administrations: [

` + by[c].map(a => "  " + val(a, "  ")).join(",\n\n") + `

] });
` }));
  }

  /* THE FORUMS AND THE WORLD'S RESOLUTIONS SHARE A FILE (design/43), as the
     parties and their currents do; a campaign's resolutions are kept in its
     folder like any other kind. */
  function forumsFile(forums, resolutions) {
    return list("FORUMS", forums, H.forums) + "\n" +
      list("RESOLUTIONS", resolutions,
`/* The world's resolutions. A campaign's are in its folder
   (content/campaigns/<id>/resolutions.js). */`);
  }
  function forumsFiles(forums, resolutions) {
    return split("resolutions", resolutions || [], w => forumsFile(forums || [], w))
      .map((f, i) => i === 0 ? { path: "content/forums.js", text: f.text } : f);
  }

  function partiesFile(parties, currents) {
    return list("PARTIES", parties, H.parties) + "\n" +
      list("CURRENTS", currents,
`/* CURRENTS — factions inside a party. Same four axes; a current
   that drifts far enough simply becomes a party above. */`);
  }

  function encyclopediaFile(enc) {
    return `/* =============================================================
   THE CONCORDANCE — in-world encyclopedia. Generated by the editor.

   A VIEW over content that already exists: parties, stations, bills,
   characters and glossary terms all get articles generated from their
   own data, with numbers read live from state. Hand-write an entry
   here only for prose the data cannot produce — history, controversy,
   the argument about the thing.

   IT IS NOT NEUTRAL. Banners are characterisation.
   ============================================================= */

const ENCYCLOPEDIA = {

  meta: ` + val(enc.meta, "  ") + `,

  /* Banner types. Keep this list short — each one is a piece of characterisation. */
  banners: ` + val(enc.banners, "  ") + `,

  /* Hand-written articles. Anything not listed is generated from data. */
  articles: [

` + enc.articles.map(a => "  " + val(a, "  ")).join(",\n\n") + `

  ]
};
`;
  }

  return { file, files, campaignFile, partiesFile, encyclopediaFile, encyclopediaFiles,
           administrationsFiles, forumsFile, forumsFiles, home, val };
})();
if (typeof module !== "undefined") module.exports = Serialise;
