/* =============================================================
   ENCODE A RECORDING FOR THE ANTHEM SLOT

     node tools/encodeaudio.js img/audio/la_bionda.ogg la_bionda \
          "La Bionda — One for You, One for Me"

   Writes content/anthem.js: the recording as base64 inside a .js file.

   WHY BASE64 AND NOT A FILE. On file://, fetch() and XMLHttpRequest both
   fail and <script src> does not, so a track cannot be loaded at run time.
   js/music.js decodes this with atob into decodeAudioData, which is the one
   route that works from disk — the same reason all content is .js.

   ONE ENTRY PER RUN. The file it writes holds a single track; a second
   recording is a second run with a different id, then merge the entries by
   hand or keep one. The introduction asks for a track by key, so nothing
   in js/ names one.

   THE SOURCE STAYS OUT OF THE BUILD. Only content/anthem.js ships; the
   OGG/WAV/MP3 is the master you re-encode from, and is worth keeping but
   does not need committing beside its own base64.
   ============================================================= */
const fs = require("fs"), path = require("path");
const root = path.join(__dirname, "..");

const args = process.argv.slice(2).filter(a => !a.startsWith("--"));
const src = args[0], id = args[1];
const title = args.slice(2).join(" ");

if (!src || !id) {
  console.error("usage: node tools/encodeaudio.js <audio-file> <track-id> [title]");
  process.exit(1);
}
const srcPath = path.join(root, src);
if (!fs.existsSync(srcPath)) {
  console.error(`Not found: ${src}\n\nPut the recording there and run again.`);
  process.exit(1);
}

const MIME = {
  ogg: "audio/ogg", oga: "audio/ogg", opus: "audio/ogg",
  mp3: "audio/mpeg", m4a: "audio/mp4", aac: "audio/aac",
  wav: "audio/wav", webm: "audio/webm", flac: "audio/flac"
};
const ext = path.extname(src).slice(1).toLowerCase();
const mime = MIME[ext];
if (!mime) {
  console.error(`Unknown audio extension ".${ext}". Known: ${Object.keys(MIME).join(", ")}`);
  process.exit(1);
}

const bytes = fs.readFileSync(srcPath);
const b64 = bytes.toString("base64");

/* Wrap so the file stays diffable and an editor does not choke on one
   five-megabyte line. The joins keep the spaces, so nothing fuses. */
const CHUNK = 120;
const lines = [];
for (let i = 0; i < b64.length; i += CHUNK) lines.push(b64.slice(i, i + CHUNK));
const data = lines.map((l, i) =>
  "      \"" + l + "\"" + (i < lines.length - 1 ? " +" : "")).join("\n");

const out =
"/* ANTHEM — the one recorded track the terminal can play.\n" +
"\n" +
"   THE SAME REASON CONTENT IS .JS: on file://, fetch() and XMLHttpRequest\n" +
"   both fail and <script src> does not, so a recording cannot be loaded as\n" +
"   a file at run time. It is base64 here and js/music.js decodes it with\n" +
"   atob into decodeAudioData, which is the only route that works from disk.\n" +
"\n" +
"   THE RECORDING IS AN ASSET, NOT A RULE, so the engine names no track. The\n" +
"   introduction asks for one by key — `intro.anthem` in content/setup.js —\n" +
"   and this file answers. An empty `data` is not an error: the game ships\n" +
"   before the recording does, and a missing track simply leaves the bed in\n" +
"   charge, exactly as the set piece's art slot renders empty.\n" +
"\n" +
"   GENERATED by tools/encodeaudio.js from " + src + ". Do not hand-edit the\n" +
"   `data` run. A second recording is a second entry, not a second mechanism.\n" +
"   `level` is where the recording sits on the music bus; the bed is mixed\n" +
"   quiet, so a full-scale track has to come down to sit over it. */\n" +
"const ANTHEM = {\n" +
"  " + JSON.stringify(id) + ": {\n" +
"    title: " + JSON.stringify(title || id) + ",\n" +
"    mime: " + JSON.stringify(mime) + ",\n" +
"    level: 0.3,\n" +
"    data:\n" + data + "\n" +
"  }\n" +
"};\n";

const outPath = path.join(root, "content/anthem.js");
fs.writeFileSync(outPath, out, "utf8");
console.log("ENCODE ANTHEM");
console.log("=".repeat(46));
console.log(`  source        ${src}`);
console.log(`  track id      ${id}`);
console.log(`  mime          ${mime}`);
console.log(`  audio bytes   ${bytes.length.toLocaleString()}`);
console.log(`  base64 chars  ${b64.length.toLocaleString()}`);
console.log(`  written       content/anthem.js (${out.length.toLocaleString()} chars)`);
console.log("\n  check it with:  npm run check");
