/* =============================================================
   toc.js — keeps bible.md navigable, and keeps it honest.

   bible.md is 1,700 lines of canon that gets read a section at a
   time, so what it needs is not a pretty contents page but a line
   index: "§4.8 is at L359" turns a full read into a ten-line one.
   The index is generated, never hand-maintained, because a stale
   line number is worse than none.

   textbook.md is treated differently on purpose. Its CONTENTS is
   in-world — a real book's contents page, written by Charnock —
   so nothing is stamped into it. This checks that it still lists
   the chapters the file actually contains, and will print a line
   index to stdout for anyone who wants one, but it does not edit
   the prose.

     node tools/toc.js            regenerate, then verify
     node tools/toc.js --check    verify only; nonzero if stale
     node tools/toc.js --index F  print a line index for any file
   ============================================================= */

const fs = require("fs");

const OPEN = "<!-- TOC — generated by tools/toc.js. Do not edit by hand. -->";
const SHUT = "<!-- /TOC -->";

const ROMAN = { I:1, II:2, III:3, IV:4, V:5, VI:6, VII:7, VIII:8, IX:9, X:10,
                XI:11, XII:12, XIII:13, XIV:14, XV:15, XVI:16 };

/* A heading is either a PART (# PART IV — …) or a section (## 4.8 … / ### 4.6.4 …).
   The status suffix (— LOCKED, — OPEN, — LEANING) is worth carrying into the
   index: it is the single most useful thing to know before opening a section. */
function headings(text) {
  const out = [];
  text.split("\n").forEach((line, i) => {
    const m = /^(#{1,3}) (.+?)\s*$/.exec(line);
    if (!m) return;
    const depth = m[1].length, title = m[2];
    const part = /^PART\s+([IVX]+)\b\s*[—-]?\s*(.*)$/.exec(title);
    if (depth === 1 && part) {
      out.push({ kind:"part", num:ROMAN[part[1]], roman:part[1],
                 title:part[2].trim(), line:i + 1 });
      return;
    }
    if (depth === 1) { out.push({ kind:"part", num:null, title, line:i + 1 }); return; }
    const sec = /^(\d+(?:\.\d+)*)\s+(.*)$/.exec(title);
    if (sec) {
      const s = /^(.*?)\s+[—-]\s+(LOCKED.*|OPEN.*|LEANING.*)$/.exec(sec[2]);
      out.push({ kind:"section", num:sec[1], title:(s ? s[1] : sec[2]).trim(),
                 status:s ? s[2] : "", line:i + 1 });
    }
  });
  return out;
}

function render(hs) {
  const L = [OPEN, "",
    "**Section index.** Generated. Line numbers are for reading a section",
    "without reading the file: `sed -n '274,290p' bible.md`. Status is the",
    "section's own — LOCKED means settled canon, OPEN means genuinely undecided.",
    ""];
  let open = false;
  hs.forEach(h => {
    if (h.kind === "part") {
      if (open) L.push("");
      L.push(`**${h.roman ? "Part " + h.roman + " — " : ""}${h.title}** · L${h.line}`);
      open = true;
    } else {
      const st = h.status ? `  *${h.status.split(",")[0]}*` : "";
      L.push(`- §${h.num} · L${h.line} — ${h.title}${st}`);
    }
  });
  L.push("", SHUT);
  return L.join("\n");
}

/* Regenerating changes the block's own length, which moves every line number
   below it. Iterate to a fixed point rather than trying to predict the offset. */
function retoc(file) {
  let text = fs.readFileSync(file, "utf8");
  if (text.indexOf(OPEN) < 0) {
    const at = text.indexOf("\n# PART 0");
    if (at < 0) throw new Error(file + ": no PART 0 to anchor the index above");
    text = text.slice(0, at + 1) + OPEN + "\n" + SHUT + "\n\n" + text.slice(at + 1);
  }
  for (let pass = 0; pass < 10; pass++) {
    const a = text.indexOf(OPEN), b = text.indexOf(SHUT) + SHUT.length;
    const next = text.slice(0, a) + render(headings(text)) + text.slice(b);
    if (next === text) return { text, passes: pass };
    text = next;
  }
  throw new Error(file + ": index did not settle");
}

/* Out-of-order sections are a real defect in a file this size — §3.9 sitting
   above §3.8 means anyone reading in order reads them backwards. Report, do
   not fix: reordering canon prose is an editorial decision, not a tool's. */
function disorder(hs) {
  const bad = [];
  const key = n => n.split(".").map(Number);
  for (let i = 1; i < hs.length; i++) {
    const p = hs[i - 1], c = hs[i];
    if (p.kind !== "section" || c.kind !== "section") continue;
    const a = key(p.num), b = key(c.num);
    if (a[0] !== b[0]) continue;
    for (let d = 0; d < Math.max(a.length, b.length); d++) {
      const x = a[d] || 0, y = b[d] || 0;
      if (x < y) break;
      if (x > y) { bad.push(`§${c.num} follows §${p.num}`); break; }
    }
  }
  return bad;
}

/* The textbook's contents page is prose. Check it, never write it.

   LINE ENDINGS ARE NOT A FACT ABOUT THE PROSE. This check was written against
   a working copy with LF and had been failing on every machine where the file
   arrived with CRLF — Windows, and the Linux runner that checks out with
   git's autocrlf — so `npm run toc` exited nonzero, `npm run toc && npm run
   check` aborted before it ever ran the checks, and the Pages deploy failed
   for a fortnight while the local build went on reporting "healthy". The
   patterns read `\r?\n` now on both boundaries, and the em dash is matched as
   the character it is rather than as the ASCII hyphen it is not. */
function checkTextbook(file) {
  const text = fs.readFileSync(file, "utf8");
  const listed = [];
  const block = /## CONTENTS\r?\n([\s\S]*?)\r?\n---/.exec(text);
  if (block) block[1].split(/\r?\n/).forEach(l => {
    const m = /^\d+\.\s+(.*\S)/.exec(l.trim());
    if (m) listed.push(m[1].toLowerCase().replace(/[^a-z]/g, ""));
  });
  const actual = [];
  text.split(/\r?\n/).forEach(l => {
    const m = /^# [A-Z]+\s+[-\u2014]\s+(.+?)\s*$/.exec(l);
    if (m) actual.push(m[1].toLowerCase().replace(/[^a-z]/g, ""));
  });
  const bad = [];
  if (listed.length !== actual.length)
    bad.push(`contents lists ${listed.length} chapters, the file has ${actual.length}`);
  else listed.forEach((t, i) => {
    if (t !== actual[i]) bad.push(`chapter ${i + 1}: contents and heading disagree`);
  });
  return bad;
}

const arg = process.argv.slice(2);
if (arg[0] === "--index") {
  headings(fs.readFileSync(arg[1], "utf8")).forEach(h =>
    console.log(h.kind === "part" ? `\n${h.title} · L${h.line}`
                                  : `  §${h.num} · L${h.line} — ${h.title}`));
  process.exit(0);
}

const check = arg[0] === "--check";
let fail = 0;

const built = retoc("bible.md");
const onDisk = fs.readFileSync("bible.md", "utf8");
if (built.text !== onDisk) {
  if (check) { console.log("  FAIL bible.md index is stale — run `npm run toc`"); fail++; }
  else { fs.writeFileSync("bible.md", built.text); console.log("  ok   bible.md index rebuilt"); }
} else console.log("  ok   bible.md index is current");

const hs = headings(built.text);
console.log(`  ok   ${hs.filter(h => h.kind === "section").length} sections in ` +
            `${hs.filter(h => h.kind === "part").length} parts indexed`);

const dis = disorder(hs);
if (dis.length) console.log("  warn sections out of order: " + dis.join(", "));
else console.log("  ok   sections are in order");

const tb = checkTextbook("textbook.md");
if (tb.length) { console.log("  FAIL textbook.md: " + tb.join("; ")); fail++; }
else console.log("  ok   textbook.md contents matches its chapters");

if (fail) { console.log(`\n${fail} INDEX FAILURES`); process.exit(1); }
console.log("\nindex is healthy");
